name: Unit Tests

on: [push,pull_request]

jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-8.0 ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Smalltalk CI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - name: Load Image and Run Unit Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} $GITHUB_WORKSPACE/.unit.ston
        timeout-minutes: 10
      - run: echo "::set-env name=SCI_COVERAGE_FILE_LOCATION::${HOME}/.smalltalkCI/_builds/coveralls_results.json"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ env.SCI_COVERAGE_FILE_LOCATION }}
